ciagznakow = input("podaj ciąg znaków")
print("-------------------------------")
print(ciagznakow.isdecimal())
print("--2-------------------------------")
srodek = input("Podaj tekst do wyśrodkowania: ")
print(srodek.center(30,"*"))
print("---------------------------")
#komenda na usuwanie od prawej: .rstrip("tekstcousuwamodprawej")
tekst = input("Podaj tekst: ")
print(tekst.isalpha())
print(tekst.isalpha() and not tekst.islower())
print("------------------------------------------")
txt = input("Jakiś ciąg znaków: ")
print = (txt.count("na"))